// create
export const ANNOUNCEMENT_CREATE_REQUEST = "@@net.wjmshop/ANNOUNCEMENT_CREATE_REQUEST";
export const ANNOUNCEMENT_CREATE_SUCCESS = "@@net.wjmshop/ANNOUNCEMENT_CREATE_SUCCESS";
export const ANNOUNCEMENT_CREATE_INVALID = "@@net.wjmshop/ANNOUNCEMENT_CREATE_INVALID";
export const ANNOUNCEMENT_CREATE_ERROR = "@@net.wjmshop/ANNOUNCEMENT_CREATE_ERROR";
// update
export const ANNOUNCEMENT_UPDATE_REQUEST = "@@net.wjmshop/ANNOUNCEMENT_UPDATE_REQUEST";
export const ANNOUNCEMENT_UPDATE_SUCCESS = "@@net.wjmshop/ANNOUNCEMENT_UPDATE_SUCCESS";
export const ANNOUNCEMENT_UPDATE_INVALID = "@@net.wjmshop/ANNOUNCEMENT_UPDATE_INVALID";
export const ANNOUNCEMENT_UPDATE_ERROR = "@@net.wjmshop/ANNOUNCEMENT_UPDATE_ERROR";
// destroy
export const ANNOUNCEMENT_DESTROY_SUCCESS = "@@net.wjmshop/ANNOUNCEMENT_DESTROY_SUCCESS";
export const ANNOUNCEMENT_DESTROY_ERROR = "@@net.wjmshop/ANNOUNCEMENT_DESTROY_ERROR";
