// create
export const CUSTOMER_SERVICE_TASK_CREATE_REQUEST =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_CREATE_REQUEST";
export const CUSTOMER_SERVICE_TASK_CREATE_SUCCESS =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_CREATE_SUCCESS";
export const CUSTOMER_SERVICE_TASK_CREATE_INVALID =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_CREATE_INVALID";
export const CUSTOMER_SERVICE_TASK_CREATE_ERROR =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_CREATE_ERROR";
// update
export const CUSTOMER_SERVICE_TASK_UPDATE_REQUEST =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_UPDATE_REQUEST";
export const CUSTOMER_SERVICE_TASK_UPDATE_SUCCESS =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_UPDATE_SUCCESS";
export const CUSTOMER_SERVICE_TASK_UPDATE_INVALID =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_UPDATE_INVALID";
export const CUSTOMER_SERVICE_TASK_UPDATE_ERROR =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_UPDATE_ERROR";
// destroy
export const CUSTOMER_SERVICE_TASK_DESTROY_SUCCESS =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_DESTROY_SUCCESS";
export const CUSTOMER_SERVICE_TASK_DESTROY_ERROR =
  "@@net.wjmshop/CUSTOMER_SERVICE_TASK_DESTROY_ERROR";
