// create
export const EMPLOYEE_CREATE_REQUEST = "@@net.wjmshop/EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS = "@@net.wjmshop/EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_INVALID = "@@net.wjmshop/EMPLOYEE_CREATE_INVALID";
export const EMPLOYEE_CREATE_ERROR = "@@net.wjmshop/EMPLOYEE_CREATE_ERROR";
// update personal information
export const EMPLOYEE_PERSONAL_INFORMATION_UPDATE_REQUEST =
  "@@net.wjmshop/EMPLOYEE_PERSONAL_INFORMATION_UPDATE_REQUEST";
export const EMPLOYEE_PERSONAL_INFORMATION_UPDATE_SUCCESS =
  "@@net.wjmshop/EMPLOYEE_PERSONAL_INFORMATION_UPDATE_SUCCESS";
export const EMPLOYEE_PERSONAL_INFORMATION_UPDATE_INVALID =
  "@@net.wjmshop/EMPLOYEE_PERSONAL_INFORMATION_UPDATE_INVALID";
export const EMPLOYEE_PERSONAL_INFORMATION_UPDATE_ERROR =
  "@@net.wjmshop/EMPLOYEE_PERSONAL_INFORMATION_UPDATE_ERROR";
// update password
export const EMPLOYEE_PASSWORD_UPDATE_REQUEST = "@@net.wjmshop/EMPLOYEE_PASSWORD_UPDATE_REQUEST";
export const EMPLOYEE_PASSWORD_UPDATE_SUCCESS = "@@net.wjmshop/EMPLOYEE_PASSWORD_UPDATE_SUCCESS";
export const EMPLOYEE_PASSWORD_UPDATE_INVALID = "@@net.wjmshop/EMPLOYEE_PASSWORD_UPDATE_INVALID";
export const EMPLOYEE_PASSWORD_UPDATE_ERROR = "@@net.wjmshop/EMPLOYEE_PASSWORD_UPDATE_ERROR";
// update permissions
export const EMPLOYEE_PERMISSIONS_UPDATE_REQUEST =
  "@@net.wjmshop/EMPLOYEE_PERMISSIONS_UPDATE_REQUEST";
export const EMPLOYEE_PERMISSIONS_UPDATE_SUCCESS =
  "@@net.wjmshop/EMPLOYEE_PERMISSIONS_UPDATE_SUCCESS";
export const EMPLOYEE_PERMISSIONS_UPDATE_INVALID =
  "@@net.wjmshop/EMPLOYEE_PERMISSIONS_UPDATE_INVALID";
export const EMPLOYEE_PERMISSIONS_UPDATE_ERROR = "@@net.wjmshop/EMPLOYEE_PERMISSIONS_UPDATE_ERROR";
// archive
export const EMPLOYEE_ARCHIVE_SUCCESS = "@@net.wjmshop/EMPLOYEE_ARCHIVE_SUCCESS";
export const EMPLOYEE_ARCHIVE_ERROR = "@@net.wjmshop/EMPLOYEE_ARCHIVE_ERROR";
// unarchive
export const EMPLOYEE_UNARCHIVE_SUCCESS = "@@net.wjmshop/EMPLOYEE_UNARCHIVE_SUCCESS";
export const EMPLOYEE_UNARCHIVE_ERROR = "@@net.wjmshop/EMPLOYEE_UNARCHIVE_ERROR";
