// create
export const MERCHANT_PLATFORM_CREATE_REQUEST = "@@net.wjmshop/MERCHANT_PLATFORM_CREATE_REQUEST";
export const MERCHANT_PLATFORM_CREATE_SUCCESS = "@@net.wjmshop/MERCHANT_PLATFORM_CREATE_SUCCESS";
export const MERCHANT_PLATFORM_CREATE_INVALID = "@@net.wjmshop/MERCHANT_PLATFORM_CREATE_INVALID";
export const MERCHANT_PLATFORM_CREATE_ERROR = "@@net.wjmshop/MERCHANT_PLATFORM_CREATE_ERROR";
// update
export const MERCHANT_PLATFORM_UPDATE_REQUEST = "@@net.wjmshop/MERCHANT_PLATFORM_UPDATE_REQUEST";
export const MERCHANT_PLATFORM_UPDATE_SUCCESS = "@@net.wjmshop/MERCHANT_PLATFORM_UPDATE_SUCCESS";
export const MERCHANT_PLATFORM_UPDATE_INVALID = "@@net.wjmshop/MERCHANT_PLATFORM_UPDATE_INVALID";
export const MERCHANT_PLATFORM_UPDATE_ERROR = "@@net.wjmshop/MERCHANT_PLATFORM_UPDATE_ERROR";
// archive
export const MERCHANT_PLATFORM_ARCHIVE_SUCCESS = "@@net.wjmshop/MERCHANT_PLATFORM_ARCHIVE_SUCCESS";
export const MERCHANT_PLATFORM_ARCHIVE_ERROR = "@@net.wjmshop/MERCHANT_PLATFORM_ARCHIVE_ERROR";
// unarchive
export const MERCHANT_PLATFORM_UNARCHIVE_SUCCESS =
  "@@net.wjmshop/MERCHANT_PLATFORM_UNARCHIVE_SUCCESS";
export const MERCHANT_PLATFORM_UNARCHIVE_ERROR = "@@net.wjmshop/MERCHANT_PLATFORM_UNARCHIVE_ERROR";
