// create
export const PAYMENT_GATEWAY_CREATE_REQUEST = "@@net.wjmshop/PAYMENT_GATEWAY_CREATE_REQUEST";
export const PAYMENT_GATEWAY_CREATE_SUCCESS = "@@net.wjmshop/PAYMENT_GATEWAY_CREATE_SUCCESS";
export const PAYMENT_GATEWAY_CREATE_INVALID = "@@net.wjmshop/PAYMENT_GATEWAY_CREATE_INVALID";
export const PAYMENT_GATEWAY_CREATE_ERROR = "@@net.wjmshop/PAYMENT_GATEWAY_CREATE_ERROR";
// update
export const PAYMENT_GATEWAY_UPDATE_REQUEST = "@@net.wjmshop/PAYMENT_GATEWAY_UPDATE_REQUEST";
export const PAYMENT_GATEWAY_UPDATE_SUCCESS = "@@net.wjmshop/PAYMENT_GATEWAY_UPDATE_SUCCESS";
export const PAYMENT_GATEWAY_UPDATE_INVALID = "@@net.wjmshop/PAYMENT_GATEWAY_UPDATE_INVALID";
export const PAYMENT_GATEWAY_UPDATE_ERROR = "@@net.wjmshop/PAYMENT_GATEWAY_UPDATE_ERROR";
// archive
export const PAYMENT_GATEWAY_ARCHIVE_SUCCESS = "@@net.wjmshop/PAYMENT_GATEWAY_ARCHIVE_SUCCESS";
export const PAYMENT_GATEWAY_ARCHIVE_ERROR = "@@net.wjmshop/PAYMENT_GATEWAY_ARCHIVE_ERROR";
// unarchive
export const PAYMENT_GATEWAY_UNARCHIVE_SUCCESS = "@@net.wjmshop/PAYMENT_GATEWAY_UNARCHIVE_SUCCESS";
export const PAYMENT_GATEWAY_UNARCHIVE_ERROR = "@@net.wjmshop/PAYMENT_GATEWAY_UNARCHIVE_ERROR";
