// create
export const SOCIAL_MEDIA_PLATFORM_CREATE_REQUEST =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_CREATE_REQUEST";
export const SOCIAL_MEDIA_PLATFORM_CREATE_SUCCESS =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_CREATE_SUCCESS";
export const SOCIAL_MEDIA_PLATFORM_CREATE_INVALID =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_CREATE_INVALID";
export const SOCIAL_MEDIA_PLATFORM_CREATE_ERROR =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_CREATE_ERROR";
// update
export const SOCIAL_MEDIA_PLATFORM_UPDATE_REQUEST =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_UPDATE_REQUEST";
export const SOCIAL_MEDIA_PLATFORM_UPDATE_SUCCESS =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_UPDATE_SUCCESS";
export const SOCIAL_MEDIA_PLATFORM_UPDATE_INVALID =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_UPDATE_INVALID";
export const SOCIAL_MEDIA_PLATFORM_UPDATE_ERROR =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_UPDATE_ERROR";
// archive
export const SOCIAL_MEDIA_PLATFORM_ARCHIVE_SUCCESS =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_ARCHIVE_SUCCESS";
export const SOCIAL_MEDIA_PLATFORM_ARCHIVE_ERROR =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_ARCHIVE_ERROR";
// unarchive
export const SOCIAL_MEDIA_PLATFORM_UNARCHIVE_SUCCESS =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_UNARCHIVE_SUCCESS";
export const SOCIAL_MEDIA_PLATFORM_UNARCHIVE_ERROR =
  "@@net.wjmshop/SOCIAL_MEDIA_PLATFORM_UNARCHIVE_ERROR";
