// create
export const SOCIAL_MEDIA_TASK_CREATE_REQUEST = "@@net.wjmshop/SOCIAL_MEDIA_TASK_CREATE_REQUEST";
export const SOCIAL_MEDIA_TASK_CREATE_SUCCESS = "@@net.wjmshop/SOCIAL_MEDIA_TASK_CREATE_SUCCESS";
export const SOCIAL_MEDIA_TASK_CREATE_INVALID = "@@net.wjmshop/SOCIAL_MEDIA_TASK_CREATE_INVALID";
export const SOCIAL_MEDIA_TASK_CREATE_ERROR = "@@net.wjmshop/SOCIAL_MEDIA_TASK_CREATE_ERROR";
// update
export const SOCIAL_MEDIA_TASK_UPDATE_REQUEST = "@@net.wjmshop/SOCIAL_MEDIA_TASK_UPDATE_REQUEST";
export const SOCIAL_MEDIA_TASK_UPDATE_SUCCESS = "@@net.wjmshop/SOCIAL_MEDIA_TASK_UPDATE_SUCCESS";
export const SOCIAL_MEDIA_TASK_UPDATE_INVALID = "@@net.wjmshop/SOCIAL_MEDIA_TASK_UPDATE_INVALID";
export const SOCIAL_MEDIA_TASK_UPDATE_ERROR = "@@net.wjmshop/SOCIAL_MEDIA_TASK_UPDATE_ERROR";
// destroy
export const SOCIAL_MEDIA_TASK_DESTROY_SUCCESS = "@@net.wjmshop/SOCIAL_MEDIA_TASK_DESTROY_SUCCESS";
export const SOCIAL_MEDIA_TASK_DESTROY_ERROR = "@@net.wjmshop/SOCIAL_MEDIA_TASK_DESTROY_ERROR";
